# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=30)),
                ('developer', models.CharField(default='default', max_length=30)),
                ('platform', models.CharField(default='default', max_length=30)),
                ('versions', models.CharField(default='default', max_length=30)),
                ('rating', models.CharField(default='default', max_length=30)),
            ],
        ),
    ]
